services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: algrano # Nombre de la base de datos por defecto
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "empleadodb"
      MYSQL_PASSWORD: "algranodb"
    volumes:
      - ./mysql-data:/var/lib/mysql # Persistencia de los datos en tu máquina local
    ports:
      - "3306:3306" # Exponer el puerto 3306 de MySQL
    networks:
      - app-network

  php:
    image: php:8.2-apache # Imagen oficial de PHP con Apache
    container_name: php
    volumes:
      - ./src:/var/www/html # El código fuente de tu proyecto PHP
    ports:
      - "8080:80" # Acceder al servidor PHP en el puerto 8080
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # Nombre del contenedor MySQL
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8081:80" # Acceder a phpMyAdmin desde http://localhost:8081
    networks:
      - app-network

  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx

networks:
  app-network:
    driver: bridge